apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name:  demo-service-hpa
spec:
  maxReplicas: 2
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  demo-service

