---
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: pymtrespsvc-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: payment-response-service
  #resourcePolicy:
  #  containerPolicies:
  #    - containerName: '*'
  #      minAllowed:
  #        cpu: 100m
  #        memory: 50Mi
  #      maxAllowed:
  #        cpu: 1
  #        memory: 500Mi
  #      controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Off"
