apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default:
      cpu: 0.75
      memory: 512Mi
    defaultRequest:
      cpu: 0.25
      memory: 256Mi
    max:
      cpu: "1000m"
      memory: 1Gi
    min:
      cpu: "200m"
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-mongo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi

