apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: gce-claim
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: null
    resources:
        requests:
            storage: 10Gi