version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    grafana_data: {}

services:

  grafana:
    image: grafana/grafana:7.1.0
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - 3000:3000  
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
