apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        envFrom:
        - configMapRef:
            name: postgres-configuration
        ports:
        - containerPort: 5432
          name: postgresdb
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: postgres-pv-claim
---
    # kind: PersistentVolume
    # apiVersion: v1
    # metadata:
    #   name: postgres-pv-volume
    #   labels:
    #     type: local
    #     app: postgres
    # spec:
    #   storageClassName: manual
    #   capacity:
    #     storage: 5Gi
    #   accessModes:
    #     - ReadWriteMany
    #   hostPath:
    #     path: "/mnt/data"
---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: postgres-pv-claim
      labels:
        app: postgres
    spec:
      storageClassName: null
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
    
---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: postgres-configuration
      labels:
        app: postgres
    data:
      POSTGRES_DB: pymtresp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ecssupport09
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    nodePort: 30432
    name: postgres
  type: NodePort 
  selector:
    app: postgres
    
    
