apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    route:
      match:
        - receiver: "slack"
    receivers:
      - name: "slack"
        slack:
          token: "slack_token"
          channel: "slack_channel"
          message: "Received a Kubernetes Event {{ .Message }}"
          fields:
            namespace: "{{ .Namespace }}"
            reason: "{{ .Reason }}"
            object: "{{ .Namespace }}"
